server:
  port: 9000

spring:
  cloud:
    config:
      server:
        git :
          uri: https://github.com/vichar/springdeanconflict.git

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.1.3:8761/eureka/